Restore the custom attribute sections
w3c/epub-specs pull request #1756
Opened 2021-07-09 15:17 UTC by mattgarrish

Also adds @iherman's suggested text about rs-specific nature of the attributes. I've made this a note, though, as it's more describing future process.

Only other change was to use "domain" instead of "authority component" in the part about the restricted strings so we can reference the URL standard instead of RFC3186.

2021-07-09 16:07 UTC, iherman approved these changes
I just wonder whether, for reasons of symmetry, we should not make a similar section (or factor out a common section) for SVG, too. After all, an RS may decide to have a RS-specific attribute in SVG content, too.

(I realize this is probably a technical purity issue of the spec rather than reflecting real usage out there, so I am o.k. if you decide to ignore this...)

2021-07-09 16:20 UTC, mattgarrish commented
> After all, an RS may decide to have a RS-specific attribute in SVG content, too.

We don't have this issue with SVG: https://www.w3.org/TR/SVG2/struct.html#ForeignNamespaces

HTML is more restrictive, so we had to explicitly allow foreign attributes.

2021-07-10 01:53 UTC, shiestyle approved these changes

2021-07-22 13:08 UTC, mattgarrish commented
I guess we should wait on a formal WG nod before merging this one, since it's undoing an earlier resolution.

2021-08-09 16:42 UTC, dauwhe requested changes
I think we should be more clear about what a custom attribute is (it's not quite a standard term in HTML). As far as I can tell, what EPUB has historically allowed is attributes in namespaces other than `xhtml` or `epub`. Just adding a `foo` attribute won't validate.

2021-08-13 12:15 UTC, iherman commented
> I think we should be more clear about what a custom attribute is (it's not quite a standard term in HTML). As far as I can tell, what EPUB has historically allowed is attributes in namespaces other than `xhtml` or `epub`. Just adding a `foo` attribute won't validate.

The proposed text says:

>  To facilitate this experimentation, vendors  MAY  define custom attributes for use in  XHTML Content Documents  provided they are from a foreign namespace, which is defined as a namespace [  XML-NAMES  ] that does not incorporate either of the following strings in its  domain  [  URL  ]: 
>
> * w3.org 
> * idpf.org 

For me, that makes it explicit that just `foo` won't be acceptable because it would not be in a foreign namespace.

2021-08-13 13:29 UTC, dauwhe commented
Ah, I guess I hope there would be some explanation about the namespaces in the authoring spec as well as the reading system spec. I fear content authors will see this as a license to use `<p foo="bar">` and will then wonder why it fails EPUBCheck.

2021-08-13 16:17 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-13-epub#section3) on 2021-08-13

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-13-epub#resolution2):  Merge PR 1756***

<details><summary><i>View the transcript</i></summary>

### 3. Custom Attributes 

_See github pull request [#1756](https://github.com/w3c/epub-specs/pull/1756)._




**Dave Cramer:** we took out the custom attributes section, but it turns out there are RS that use these  
… so now we want to put it back  

**Dan Lazin:** can we get some documentation on what exists in terms of custom attributes? So people can make use of them in their books?  

**Dave Cramer:** we can see about including some examples  

> **Proposed resolution: Merge PR 1756** *(Wendy Reid)*

> *Dave Cramer:* +1

> *Wendy Reid:* +1

> *Dan Lazin:* +1

> *Matthew Chan:* +1

> *Ivan Herman:* +1

> *Charles LaPierre:* +1

> *Ben Schroeter:* +1

> *Brady Duga:* +1

> *Masakazu Kitahara:* +1

> ***Resolution #2: Merge PR 1756***

**Dave Cramer:** okay, thanks everyone!  

---


</details>

2021-08-15 07:20 UTC, iherman commented
> Ah, I guess I hope there would be some explanation about the namespaces in the authoring spec as well as the reading system spec. I fear content authors will see this as a license to use `<p foo="bar">` and will then wonder why it fails EPUBCheck.

@dauwhe I do not think the normative statements should be changed. But I have added an extra note right after the list of domains, as follows:

> Note that this restriction also disallows the usage of custom attributes without a namespace prefix 
> (e.g., <code>&lt;p foo=""&gt;…&lt;/p&gt;</code>). Indeed, such attributes are considered to be part of
> the default namespace, i.e., either the XHTML or SVG namespaces, which are both in the <code>w3.org</code> domain.

2021-08-18 10:06 UTC, iherman commented
@dauwhe are you o.k. with https://github.com/w3c/epub-specs/pull/1756#issuecomment-899008259? We could then close this PR

2021-08-18 13:07 UTC, dauwhe approved these changes

2021-08-18 13:08 UTC, merged