FXL A11y Issues
w3c/epub-specs pull request #2043
Opened 2022-03-08 15:12 UTC by wareid

Addressing the issues raised with the FXL A11y document in issue #s #2012, #2014, #2015, #2016, and #2017.

2022-03-09 12:13 UTC, mattgarrish submitted a review, later dismissed
Noticed one typo, otherwise seems fine. I'll let @clapierre determine if it fixes all the issues he opened, though.

2022-03-09 12:13 UTC, mattgarrish commented on epub33/fxl-a11y/index.html
> +One challenge with fixed layouts is finding ways to describe the image and provide context given that there is no extra area on the page users can access in which to place a description. The other ch
s/it's/its/

2022-03-09 14:51 UTC, clapierre approved these changes
much better!

2022-03-10 01:51 UTC, murata2makoto commented
Text rasterization causes big A11Y problems, but it is considered unavoidable.  It would be better if we can have some wording about why text rasterization cannot be easily avoided and what we should do to overcome this problem.

2022-03-10 01:55 UTC, murata2makoto requested changes
Text rasterization causes big A11Y problems, but it is considered unavoidable. It would be better if we can have some wording about why text rasterization cannot be easily avoided and what we should do to overcome this problem.

2022-03-16 15:00 UTC, wareid commented
@mattgarrish @murata2makoto Please review the revised text please!

2022-03-17 23:33 UTC, murata2makoto requested changes
Thank you so much, Wendy.  But this is such an important and long-lasting problem, especially in Japan, I would like to be very thorough.

First, I would like to mention rasterized text in the first paragraph.  For example:

- Images may contain rasterized text and sophisticated layout (scholarly
publishing, for example) (Note: Do we have a list of genres for FXL publications?)

Second, I do not believe that alt text is good enough for image-dominated FXL publications.  Several attempts have been made (e.g, longdesc of HTML and multiple-renditions of EPUB) but none of them are successful, unfortunately.  I would like to explicitly mention this shortcoming in our family of specifications and encourage future improvements.

2022-03-22 14:08 UTC, wareid commented
@murata2makoto I've added a little more detail. I think more work needs to be done to this section, but I'd like to close this PR for now. 

We do have a list of genres for FXL publications, we're working on accompanying examples and most of that work will go there, including some work around different methods for image description.

2022-03-22 14:08 UTC, merged