Update conformance identifiers to new expanded pattern
w3c/epub-specs pull request #2400
Opened 2022-08-12 11:19 UTC by mattgarrish

This pull request implements the new pattern for identifiers we discussed to make the metadata field more human readable.

Because the value now has whitespace in it, I added that the value must match our pattern string after xml whitespace normalization. This will allow the value to be brokan by line endings and indents but still be valid.

Other than that, it's a pretty basic expanding of a few abbreviations and removing the hyphenation and underscores that made it one contiguous string of characters.

Fixes #2398 

- Accessibility [preview](https://cdn.statically.io/gh/w3c/epub-specs/a11y/issue-2398/epub33/a11y/index.html)
- Accessibility [diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://w3c.github.io/epub-specs/epub33/a11y/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://cdn.statically.io/gh/w3c/epub-specs/a11y/issue-2398/epub33/a11y/index.html)

2022-08-12 14:27 UTC, clapierre approved these changes
Looks like we all agreed to, thanks Matt.

2022-08-16 08:23 UTC, gregoriopellegrino approved these changes

2022-08-24 12:05 UTC, iherman requested changes

2022-08-24 12:05 UTC, iherman commented on epub33/a11y/index.html
> +					<p class="conf-pattern">EPUB Aceessibility <a href="#acc-ver"><var>A11Y-VER</var></a> - WCAG <a
```suggestion
					<p class="conf-pattern">EPUB Accessibility <a href="#acc-ver"><var>A11Y-VER</var></a> - WCAG <a
```

2022-08-24 12:05 UTC, iherman commented on epub33/a11y/index.html
> +         EPUB Aceessibility 1.1 - WCAG 2.1 Level AA
```suggestion
         EPUB Accessibility 1.1 - WCAG 2.1 Level AA
```

2022-08-24 12:05 UTC, iherman commented on epub33/a11y/index.html
> +						<li>EPUB Aceessibility 1.1 - WCAG 2.1 Level AAA</li>
```suggestion
						<li>EPUB Accessibility 1.1 - WCAG 2.0 Level A</li>
						<li>EPUB Accessibility 1.1 - WCAG 2.0 Level AA</li>
						<li>EPUB Accessibility 1.1 - WCAG 2.0 Level AAA</li>
						<li>EPUB Accessibility 1.1 - WCAG 2.1 Level A</li>
						<li>EPUB Accessibility 1.1 - WCAG 2.1 Level AA</li>
						<li>EPUB Accessibility 1.1 - WCAG 2.1 Level AAA</li>
```

2022-08-26 15:00 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-08-26-epub#section2) on 2022-08-26

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2022-08-26-epub#resolution2):  Merge PRs 2400 and 2401.***

<details><summary><i>View the transcript</i></summary>

### 2. Changes to accessibility conformance identifiers and `accessibilitySummary`.

_See github pull request [epub-specs#2400](https://github.com/w3c/epub-specs/pull/2400)._




_See github pull request [epub-specs#2401](https://github.com/w3c/epub-specs/pull/2401)._




_See github issue [epub-specs#2399](https://github.com/w3c/epub-specs/issues/2399)._




_See github issue [epub-specs#2398](https://github.com/w3c/epub-specs/issues/2398)._




**Avneesh Singh:** the main issue here is how to handle `accessibilitySummary`.  
… should it be mandatory, or only recommended?.  
… we settled on recommended, and highlight the cases where you should definitely provide this data.  
… this also requires a change in something else. People were using this field to explain a11y conformance.  
… mgarrish suggested that we should make the conformance field more human-friendly.  
… which means you don't need to explain this in `accessibilitySummary`.  

> *Dave Cramer:* ak ch.

**Avneesh Singh:** so these are the two PRs.  

**Charles LaPierre:** agreed. In addition, mgarrish also clarified that there should only be one `accessibilitySummary`, in the language of the epub.  
… the `accessibilitySummary` is now recommended. It should include anything that is not captured in the other (machine readable) meta fields.  
… not duplication.  
… we will rewrite a11y best practices around how to display epub metadata to users.  

**George Kerscher:** the EUAA will require the presentation of a11y data, so we feel that if the other fields that are currently machine readable can be communicated to users via best practices, then accessibilitySummary can just be for anything else.  

**John Foliot:** what happens if the epub is in more than one language? Then what lang should `accessibilitySummary` be if there should only be one? Multiple languages in one?.  

**George Kerscher:** there's always a base language for the publication, so the accessibilitySummary would use that language..  

**John Foliot:** the `accessibilitySummary`, as explained, is intended to be human readable. So screen readers should be able to read it. I should be able to use tools like language tagging, pronunciation markup, etc..  
… so maybe that human readable summary should support multiple languages.  

**George Kerscher:** the name summary is inaccurate. It's not a summary of the whole document. It uses the term summary as a holdover from Schema.org.  
… we would propose to reference the Schema.org description in the a11y best practices guide, to make this clear.  

**Avneesh Singh:** a lot of the details which have been shared about a11y guidelines have been working in Publishing CG.  

**Ivan Herman:** i'm looking at preview of the spec where description of `accessibilitySummary` does not make explicit reference to languages.  

_See github issue [publ-a11y#94](https://github.com/w3c/publ-a11y/issues/94)._




**Ivan Herman:** also `accessibilitySummary` is part of the package document, so you can repeat it in a different language?.  

**Wendy Reid:** there's a note in the PR about not repeating the `accessibilitySummary`.  
… "do not repeat this property to declare translations...".  
… since there is no hierarchy, the RS might pick the wrong language.  

**Ivan Herman:** it's an xml document, so adding a language is technically possible.  

**Avneesh Singh:** we've been discussing `accessibilitySummary` for a couple months now, JF has made good points but we are in CR now. We will defer these things to the next version rather than expanding our work on this currently.  

**Wendy Reid:** any other questions re. `accessibilitySummary`? Changes to conformance identifiers?.  

> **Proposed resolution: Merge PRs 2400 and 2401.** *(Wendy Reid)*

> *Ivan Herman:* +1.

> *Charles LaPierre:* +1.

> *Wendy Reid:* +1.

> *Matthew Chan:* +1.

> *Avneesh Singh:* +1.

> *Brady Duga:* +1.

> *Masakazu Kitahara:* +1.

> *Dave Cramer:* +1.

> ***Resolution #2: Merge PRs 2400 and 2401.***

</details>

2022-08-27 11:24 UTC, merged