Clarify decimal values are allowed in viewport meta declarations
w3c/epub-specs pull request #2573
Opened 2023-07-20 17:39 UTC by mattgarrish

Replaces "positive number" with "positive decimal number" in the authoring restrictions and adds that reading systems may ignore the fractional part.

@iherman My math is rusty, but as far as I recall 1,2,3...n are decimal numbers because the fractional part can be dropped if it is 0. Let me know if I've got that wrong, though! The alternative was to make it something like "positive integer or decimal number", but that seems redundant if I have the above right.

(I'm not 100% sure what to do about change logs, so have omitted entries for now. Will need to update before merging.)

Fixes #2557 

* [Preview](https://cdn.statically.io/gh/w3c/epub-specs/fix/issue-2557/epub33/rs/index.html)
* [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://w3c.github.io/epub-specs/epub33/rs/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://cdn.statically.io/gh/w3c/epub-specs/fix/issue-2557/epub33/rs/index.html)

2023-07-20 19:21 UTC, mattgarrish commented
I've updated the pull request and revised the first comment to reflect the changes. All this does now is add a link to the CSS definition of number as additional clarification. These values are defining the CSS ICB, so it's not really changing anything substantive.

2023-07-21 06:45 UTC, iherman approved these changes

2023-07-26 00:48 UTC, shiestyle approved these changes

2023-07-26 13:51 UTC, rdeltour requested changes
I'm confused about which `number` definition should be referenced here.

The PR currently refers to the CSS 2.1 definition, but as EPUB refers to CSS snapshot, isn't this definition overridden by the one in [CSS Values and Units Level 3](https://www.w3.org/TR/css-values-3/#numbers)? (which is being slightly corrected in [Level 4](https://drafts.csswg.org/css-values/#numbers)).

Note by the way that the new definition allows scientific notation (for instance `10e3` is a valid CSS number). Do we know if these are supported in viewport dimensions?

2023-08-09 10:32 UTC, merged