Addressing APA feedback in FXL Accessibility Document
w3c/epub-specs pull request #2659
Opened 2024-10-21 14:17 UTC by wareid

This PR includes some edits to address the feedback we received regarding the FXL Accessibility document from APA during our session with them at TPAC. 

Two main changes: 
1. Adjusted the name of the document to include "Best Practices" to avoid confusion around conformance. 
2. Added text to further clarify the reading order section, including noting the difference between EPUB's concept of reading order and accessibility's concept of reading order. 

Feedback welcome!

2024-10-21 14:21 UTC, iherman approved these changes

2024-10-21 15:08 UTC, gautierchomel commented
[Preview](https://rawcdn.githack.com/w3c/epub-specs/05215956a4bb65b1604a3df00cf38ad1c44d37de/epub33/fxl-a11y/index.html)

2024-10-21 15:20 UTC, mattgarrish commented on epub33/fxl-a11y/index.html
> +            <p>Reading order in EPUB refers to the order of content documents in the <a href="https://www.w3.org/TR/epub-33/#sec-pkg-spine"><code>spine</code></a> section of the <a href="https://www.
Minor nit, but package doesn't need to be capitalized. I'd also link the full term.

```suggestion
            <p>Reading order in EPUB refers to the order of content documents in the <a href="https://www.w3.org/TR/epub-33/#sec-pkg-spine"><code>spine</code></a> section of the <a href="https://www.w3.org/TR/epub-33/#sec-package-doc">package document</a>. However, the concept of reading order is also an important consideration for accessibility and refers to the visual and programmatic order of elements in a content document. In both EPUB and accessibility usage, reading order must be logical and accurate both visually and programmatically.</p>
```

2024-10-21 15:48 UTC, gautierchomel commented
To me, the document still mix too many different problems for different audiences:
* A technical approach to address machine reading (today Screen readers, but probably tomorrow, an _On the fly reflow_ performed by a reading system);
* Design oriented recommendations (section 2.5 Legibility and Visual Presentation);
* Rendering of Fixed Layout by a Reading System.

2024-10-22 08:42 UTC, avneeshsingh requested changes
Regarding the title, the feedback from APA was to consider best practices and challenges because the document also does a good work of highlighting challenges for which we do not have a solution yet.
The recommendation was something like
EPUB fixed layout accessibility: best practices and challenges
George recommended to swap the last two words
EPUB fixed layout accessibility: challenges and best practices.
The title can be refined, but the main message for title was to mention both best practices and challenges.

2024-10-22 18:42 UTC, mattgarrish commented
What about matching the naming along the lines of our other accessibility documents and make it something like:

> EPUB Accessibility -- Fixed Layout Challenges and Best Practices

2024-10-22 19:07 UTC, GeorgeKerscher commented
I like this approach.

2024-10-23 04:45 UTC, avneeshsingh commented
This will make the document look like EPUB Accessibility 1.1. This is exactly what we want to avoid. This document is more about best practices and challenges for fixed layout. 
It will take time and significant research to reach the level where we can say that it provides techniques for meeting EPUB Accessibility specifications.

2024-10-23 11:48 UTC, mattgarrish commented
It puts it under the accessibility umbrella, but I don't think anyone would get too confused by a document called challenges and best practices.

The alternative would be to put these under the FXL umbrella, so have:

EPUB Fixed Layouts -- Accessibility Challenges and Best Practices

I think the more problematic name is going to be the techniques document. If this is best practices, how do you differentiate that document without it sounding like a proper accessibility guide. But that's a problem for another day, I suppose.

2024-10-23 12:15 UTC, avneeshsingh commented
This looks better:

“EPUB 3 Fixed Layouts -- Accessibility Challenges and Best Practices”

2024-10-23 12:58 UTC, gautierchomel commented
The key sentence of the document is in the overview:

> An accessible fixed layout EPUB file is one that meets the accessibility requirements of the Web Content Accessibility Guidelines 2.x level AA [[wcag2](https://rawcdn.githack.com/w3c/epub-specs/05215956a4bb65b1604a3df00cf38ad1c44d37de/epub33/fxl-a11y/index.html#bib-wcag2)] and EPUB Accessibility 1.1 [[epub-a11y-11](https://rawcdn.githack.com/w3c/epub-specs/05215956a4bb65b1604a3df00cf38ad1c44d37de/epub33/fxl-a11y/index.html#bib-epub-a11y-11)],

It may be more apparent to have this stated at the very beginning of the abstract section.

2024-11-19 15:00 UTC, wareid commented
See:

* For EPUB Fixed Layout Accessibility:
    * [Preview](https://cdn.statically.io/gh/w3c/epub-specs/fxl-a11y-apa-feedback/epub33/fxl-a11y/index.html)
    * [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://w3c.github.io/epub-specs/epub33/fxl-a11y/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://cdn.statically.io/gh/w3c/epub-specs/fxl-a11y-apa-feedback/epub33/fxl-a11y/index.html)

2024-11-26 12:32 UTC, gregoriopellegrino commented
The link to see the diff doesn't work...

2024-11-26 13:31 UTC, mattgarrish commented
Ya, we ran into this yesterday with the schema.org vocabulary. The spec-generator tool keeps timing out so the diff tool can't get the file to compare against. pr-preview isn't working for the same reason.

@deniak do you know if this is a temporary glitch or something that needs fixing?

2024-11-26 17:16 UTC, deniak commented
> Ya, we ran into this yesterday with the schema.org vocabulary. The spec-generator tool keeps timing out so the diff tool can't get the file to compare against. pr-preview isn't working for the same reason.
> 
> @deniak do you know if this is a temporary glitch or something that needs fixing?

It seems a recent upgrade of chromium broke spec-generator. I'll see how to fix this.

2024-11-26 17:32 UTC, deniak commented
@mattgarrish spec-generator should be back now.

2024-11-26 18:19 UTC, mattgarrish commented
Yes, the diffs are working again. Thanks!

2024-11-27 14:35 UTC, wareid commented
@avneeshsingh I have updated the document with a new name in line with @mattgarrish's suggestion, and I want to explain my reasoning why. I understand your concerns about relating it to EPUB Accessibility 1.1, but I do find the suggestion to keep this document in the same naming convention compelling, as the hope is eventually this document may be able to rise to the same level. The main blocker right now to this being a more normative document is that accessibility is not completely possible with FXL, but we are on a road to that result, so keeping this document in the "family", while making sure the title and body are clear that there remains to be challenges I think helps us achieve our goals and consistency.

@gautierchomel I have also adopted the abstract change suggested. I am going to do the reformatting of the doc in another PR as it's not related to the APA feedback.

2024-11-29 10:10 UTC, iherman commented
My apologies to be late to this particular party. I have to put my staff contact hat on: do you plan to change the official short name of the document, too? Meaning: will the documents' URL remain: https://www.w3.org/TR/epub-fxl-a11y/ ?

- If yes, than we have no problems
- If no, it becomes an admin hurdle; the publication of the first changed instance of the document will have be made manually with some additional massage (the goal is to ensure history). Doable, but a hurdle nevertheless.

Which one is it?

2024-12-02 13:55 UTC, gregoriopellegrino commented
@deniak and @mattgarrish the diff link returns "An error (I/O error: None None) occured trying to get": https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://w3c.github.io/epub-specs/epub33/fxl-a11y/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://cdn.statically.io/gh/w3c/epub-specs/fxl-a11y-apa-feedback/epub33/fxl-a11y/index.html

The problem seems to be with the URL https://labs.w3.org/spec-generator/?type=respec&url=https://cdn.statically.io/gh/w3c/epub-specs/fxl-a11y-apa-feedback/epub33/fxl-a11y/index.html that returns "Navigation timeout of 29452 ms exceeded".

Is there a better place where I can report this issue?

2024-12-02 13:58 UTC, deniak commented
> Is there a better place where I can report this issue?

For all issues related to the spec-generator, you may raise an issue on [its repository](https://github.com/w3c/spec-generator). I'll investigate on why it's failing again this time so you don't need to bother this time.

2024-12-02 14:13 UTC, mattgarrish commented
> For all issues related to the spec-generator, you may raise an issue on [its repository](https://github.com/w3c/spec-generator).

Okay, thanks!

2024-12-02 15:48 UTC, wareid commented
> My apologies to be late to this particular party. I have to put my staff contact hat on: do you plan to change the official short name of the document, too? Meaning: will the documents' URL remain: https://www.w3.org/TR/epub-fxl-a11y/ ?
> 
> * If yes, than we have no problems
> * If no, it becomes an admin hurdle; the publication of the first changed instance of the document will have be made manually with some additional massage (the goal is to ensure history). Doable, but a hurdle nevertheless.
> 
> Which one is it?

We will not be changing the short name, no worries.

2024-12-02 16:04 UTC, iherman commented
> 
> We will not be changing the short name, no worries.


Pfew 😀

2024-12-06 08:20 UTC, deniak commented
Hi all,

spec-generator should now be back again. Please let me know, if that's not the case for you.

2024-12-17 15:35 UTC, merged